### ISSUE TITLE
Company won't save correctly

### ISSUE THREAD

**Issue by RagnarTheEverchosen** [JustCodiex/coh2-battlegrounds#62]
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
PlayerCompanies: System.Text.Json.JsonException: The converter 'Battlegrounds.Game.DataCompany.CompanySerializer' read too much or not enough. Path: $ | LineNumber: 1 | BytePositionInLine: 12.
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.VerifyRead(JsonTokenType tokenType, Int32 depth, Int64 bytesConsumed, Boolean isValueConverter, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Battlegrounds.Game.DataCompany.CompanySerializer.GetCompanyFromJson(String rawJsonData) in D:\coh2_projects\coh2-battlegrounds\coh2-battlegrounds\coh2-battlegrounds-bin\Game\DataCompany\CompanySerializer.cs:line 175
   at BattlegroundsApp.LocalData.PlayerCompanies.LoadAll() in D:\coh2_projects\coh2-battlegrounds\coh2-battlegrounds\coh2-battlegrounds\LocalData\PlayerCompanies.cs:line 36

**Comment by RagnarTheEverchosen** [comment]
Could't make the bug to replicate
